apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: kafka
  namespace: dev
  labels:
    app: kafka

spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  template:
    metadata:
      namespace: dev
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.9.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
