services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web interface
    environment:
      MINIO_ROOT_USER: moonfire
      MINIO_ROOT_PASSWORD: moonfire
    command: server /data --console-address ":9001"