services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web interface
    environment:
      MINIO_ROOT_USER: moonfire
      MINIO_ROOT_PASSWORD: moonfire
      MINIO_BUCKETS: audio-raw
    command: server /data --console-address ":9001"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - "5432:5432"
  kafka:
    image: apache/kafka:latest
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=DOCKER://:9092,LOCAL://:9093,CONTROLLER://:9094
      - KAFKA_ADVERTISED_LISTENERS=DOCKER://host.docker.internal:9092,LOCAL://localhost:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,LOCAL:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=1
    ports:
      - '9092:9092'
      - '9093:9093'
  tg-bot:
    image: bot
    build:
      context: ./services/bot
    environment:
      S3_ACCESS_KEY_ID: moonfire
      S3_SECRET_ACCESS_KEY: moonfire
      S3_URL: http://s3:9000

      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: postgres

      KAFKA_BOOTSTRAP_SERVERS: '["kafka:9092"]'
      KAFKA_CONSUMER_GROUP: tg_bot

      DEFAULT_LOCALE: en

      BOT_TOKEN: "${BOT_TOKEN}"
      BOT_API_MODE: "webhook"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
    depends_on:
      - postgres
      - s3
      - kafka
    ports:
      - '9090:9090'
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http --domain=${NGROK_BASE_URL} tg-bot:8080
    depends_on:
      - tg-bot
