# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tgdb_pb2 as tgdb__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tgdb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TgDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/tgdb.TgDB/CreateUser',
                request_serializer=tgdb__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=tgdb__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.GetUserByID = channel.unary_unary(
                '/tgdb.TgDB/GetUserByID',
                request_serializer=tgdb__pb2.GetUserByIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.GetUserByIDResponse.FromString,
                _registered_method=True)
        self.GetUserByTgID = channel.unary_unary(
                '/tgdb.TgDB/GetUserByTgID',
                request_serializer=tgdb__pb2.GetUserByTgIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.GetUserByTgIDResponse.FromString,
                _registered_method=True)
        self.UpdateUserByID = channel.unary_unary(
                '/tgdb.TgDB/UpdateUserByID',
                request_serializer=tgdb__pb2.UpdateUserByIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.UpdateUserByIDResponse.FromString,
                _registered_method=True)
        self.UpdateUserByTgID = channel.unary_unary(
                '/tgdb.TgDB/UpdateUserByTgID',
                request_serializer=tgdb__pb2.UpdateUserByTgIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.UpdateUserByTgIDResponse.FromString,
                _registered_method=True)
        self.DeleteUserByID = channel.unary_unary(
                '/tgdb.TgDB/DeleteUserByID',
                request_serializer=tgdb__pb2.DeleteUserByIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.DeleteUserByIDResponse.FromString,
                _registered_method=True)
        self.DeleteUserByTgID = channel.unary_unary(
                '/tgdb.TgDB/DeleteUserByTgID',
                request_serializer=tgdb__pb2.DeleteUserByTgIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.DeleteUserByTgIDResponse.FromString,
                _registered_method=True)
        self.GetUserID = channel.unary_unary(
                '/tgdb.TgDB/GetUserID',
                request_serializer=tgdb__pb2.GetUserIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.GetUserIDResponse.FromString,
                _registered_method=True)
        self.GetUserTgID = channel.unary_unary(
                '/tgdb.TgDB/GetUserTgID',
                request_serializer=tgdb__pb2.GetUserTgIDRequest.SerializeToString,
                response_deserializer=tgdb__pb2.GetUserTgIDResponse.FromString,
                _registered_method=True)


class TgDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByTgID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserByTgID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserByTgID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserTgID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TgDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=tgdb__pb2.CreateUserRequest.FromString,
                    response_serializer=tgdb__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetUserByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByID,
                    request_deserializer=tgdb__pb2.GetUserByIDRequest.FromString,
                    response_serializer=tgdb__pb2.GetUserByIDResponse.SerializeToString,
            ),
            'GetUserByTgID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByTgID,
                    request_deserializer=tgdb__pb2.GetUserByTgIDRequest.FromString,
                    response_serializer=tgdb__pb2.GetUserByTgIDResponse.SerializeToString,
            ),
            'UpdateUserByID': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserByID,
                    request_deserializer=tgdb__pb2.UpdateUserByIDRequest.FromString,
                    response_serializer=tgdb__pb2.UpdateUserByIDResponse.SerializeToString,
            ),
            'UpdateUserByTgID': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserByTgID,
                    request_deserializer=tgdb__pb2.UpdateUserByTgIDRequest.FromString,
                    response_serializer=tgdb__pb2.UpdateUserByTgIDResponse.SerializeToString,
            ),
            'DeleteUserByID': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserByID,
                    request_deserializer=tgdb__pb2.DeleteUserByIDRequest.FromString,
                    response_serializer=tgdb__pb2.DeleteUserByIDResponse.SerializeToString,
            ),
            'DeleteUserByTgID': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserByTgID,
                    request_deserializer=tgdb__pb2.DeleteUserByTgIDRequest.FromString,
                    response_serializer=tgdb__pb2.DeleteUserByTgIDResponse.SerializeToString,
            ),
            'GetUserID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserID,
                    request_deserializer=tgdb__pb2.GetUserIDRequest.FromString,
                    response_serializer=tgdb__pb2.GetUserIDResponse.SerializeToString,
            ),
            'GetUserTgID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserTgID,
                    request_deserializer=tgdb__pb2.GetUserTgIDRequest.FromString,
                    response_serializer=tgdb__pb2.GetUserTgIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tgdb.TgDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tgdb.TgDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TgDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/CreateUser',
            tgdb__pb2.CreateUserRequest.SerializeToString,
            tgdb__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/GetUserByID',
            tgdb__pb2.GetUserByIDRequest.SerializeToString,
            tgdb__pb2.GetUserByIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByTgID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/GetUserByTgID',
            tgdb__pb2.GetUserByTgIDRequest.SerializeToString,
            tgdb__pb2.GetUserByTgIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/UpdateUserByID',
            tgdb__pb2.UpdateUserByIDRequest.SerializeToString,
            tgdb__pb2.UpdateUserByIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserByTgID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/UpdateUserByTgID',
            tgdb__pb2.UpdateUserByTgIDRequest.SerializeToString,
            tgdb__pb2.UpdateUserByTgIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/DeleteUserByID',
            tgdb__pb2.DeleteUserByIDRequest.SerializeToString,
            tgdb__pb2.DeleteUserByIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUserByTgID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/DeleteUserByTgID',
            tgdb__pb2.DeleteUserByTgIDRequest.SerializeToString,
            tgdb__pb2.DeleteUserByTgIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/GetUserID',
            tgdb__pb2.GetUserIDRequest.SerializeToString,
            tgdb__pb2.GetUserIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserTgID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tgdb.TgDB/GetUserTgID',
            tgdb__pb2.GetUserTgIDRequest.SerializeToString,
            tgdb__pb2.GetUserTgIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
