// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/tgdb/internal/ports/input.go
//
// Generated by this command:
//
//	mockgen -source=./services/tgdb/internal/ports/input.go -destination=./services/tgdb/pkg/mock/mock_input.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/echo/tgdb/internal/domain/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCasePort is a mock of UseCasePort interface.
type MockUseCasePort struct {
	ctrl     *gomock.Controller
	recorder *MockUseCasePortMockRecorder
	isgomock struct{}
}

// MockUseCasePortMockRecorder is the mock recorder for MockUseCasePort.
type MockUseCasePortMockRecorder struct {
	mock *MockUseCasePort
}

// NewMockUseCasePort creates a new mock instance.
func NewMockUseCasePort(ctrl *gomock.Controller) *MockUseCasePort {
	mock := &MockUseCasePort{ctrl: ctrl}
	mock.recorder = &MockUseCasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCasePort) EXPECT() *MockUseCasePortMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUseCasePort) CreateUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUseCasePortMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUseCasePort)(nil).CreateUser), ctx, user)
}

// DeleteUserByID mocks base method.
func (m *MockUseCasePort) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByID indicates an expected call of DeleteUserByID.
func (mr *MockUseCasePortMockRecorder) DeleteUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByID", reflect.TypeOf((*MockUseCasePort)(nil).DeleteUserByID), ctx, id)
}

// DeleteUserByTgID mocks base method.
func (m *MockUseCasePort) DeleteUserByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByTgID indicates an expected call of DeleteUserByTgID.
func (mr *MockUseCasePortMockRecorder) DeleteUserByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByTgID", reflect.TypeOf((*MockUseCasePort)(nil).DeleteUserByTgID), ctx, id)
}

// GetUserByID mocks base method.
func (m *MockUseCasePort) GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUseCasePortMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUseCasePort)(nil).GetUserByID), ctx, id)
}

// GetUserByTgID mocks base method.
func (m *MockUseCasePort) GetUserByTgID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTgID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTgID indicates an expected call of GetUserByTgID.
func (mr *MockUseCasePortMockRecorder) GetUserByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTgID", reflect.TypeOf((*MockUseCasePort)(nil).GetUserByTgID), ctx, id)
}

// GetUserID mocks base method.
func (m *MockUseCasePort) GetUserID(ctx context.Context, id int64) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockUseCasePortMockRecorder) GetUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockUseCasePort)(nil).GetUserID), ctx, id)
}

// GetUserTgID mocks base method.
func (m *MockUseCasePort) GetUserTgID(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTgID", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTgID indicates an expected call of GetUserTgID.
func (mr *MockUseCasePortMockRecorder) GetUserTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTgID", reflect.TypeOf((*MockUseCasePort)(nil).GetUserTgID), ctx, id)
}

// UpdateUserByID mocks base method.
func (m *MockUseCasePort) UpdateUserByID(ctx context.Context, id uuid.UUID, update *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserByID indicates an expected call of UpdateUserByID.
func (mr *MockUseCasePortMockRecorder) UpdateUserByID(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByID", reflect.TypeOf((*MockUseCasePort)(nil).UpdateUserByID), ctx, id, update)
}

// UpdateUserByTgID mocks base method.
func (m *MockUseCasePort) UpdateUserByTgID(ctx context.Context, id int64, update *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByTgID", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserByTgID indicates an expected call of UpdateUserByTgID.
func (mr *MockUseCasePortMockRecorder) UpdateUserByTgID(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByTgID", reflect.TypeOf((*MockUseCasePort)(nil).UpdateUserByTgID), ctx, id, update)
}
