// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/tgdb/internal/ports/output.go
//
// Generated by this command:
//
//	mockgen -source=./services/tgdb/internal/ports/output.go -destination=./services/tgdb/pkg/mock/mock_output.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/echo/tgdb/internal/domain/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserCommand is a mock of UserCommand interface.
type MockUserCommand struct {
	ctrl     *gomock.Controller
	recorder *MockUserCommandMockRecorder
	isgomock struct{}
}

// MockUserCommandMockRecorder is the mock recorder for MockUserCommand.
type MockUserCommandMockRecorder struct {
	mock *MockUserCommand
}

// NewMockUserCommand creates a new mock instance.
func NewMockUserCommand(ctrl *gomock.Controller) *MockUserCommand {
	mock := &MockUserCommand{ctrl: ctrl}
	mock.recorder = &MockUserCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCommand) EXPECT() *MockUserCommandMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserCommand) Add(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockUserCommandMockRecorder) Add(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserCommand)(nil).Add), ctx, user)
}

// DeleteByID mocks base method.
func (m *MockUserCommand) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockUserCommandMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockUserCommand)(nil).DeleteByID), ctx, id)
}

// DeleteByTgID mocks base method.
func (m *MockUserCommand) DeleteByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTgID indicates an expected call of DeleteByTgID.
func (mr *MockUserCommandMockRecorder) DeleteByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTgID", reflect.TypeOf((*MockUserCommand)(nil).DeleteByTgID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockUserCommand) UpdateByID(ctx context.Context, id uuid.UUID, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockUserCommandMockRecorder) UpdateByID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockUserCommand)(nil).UpdateByID), ctx, id, user)
}

// UpdateByTgID mocks base method.
func (m *MockUserCommand) UpdateByTgID(ctx context.Context, id int64, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTgID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByTgID indicates an expected call of UpdateByTgID.
func (mr *MockUserCommandMockRecorder) UpdateByTgID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTgID", reflect.TypeOf((*MockUserCommand)(nil).UpdateByTgID), ctx, id, user)
}

// MockUserQuery is a mock of UserQuery interface.
type MockUserQuery struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueryMockRecorder
	isgomock struct{}
}

// MockUserQueryMockRecorder is the mock recorder for MockUserQuery.
type MockUserQueryMockRecorder struct {
	mock *MockUserQuery
}

// NewMockUserQuery creates a new mock instance.
func NewMockUserQuery(ctrl *gomock.Controller) *MockUserQuery {
	mock := &MockUserQuery{ctrl: ctrl}
	mock.recorder = &MockUserQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQuery) EXPECT() *MockUserQueryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserQuery) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserQueryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserQuery)(nil).GetByID), ctx, id)
}

// GetByTgID mocks base method.
func (m *MockUserQuery) GetByTgID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTgID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTgID indicates an expected call of GetByTgID.
func (mr *MockUserQueryMockRecorder) GetByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTgID", reflect.TypeOf((*MockUserQuery)(nil).GetByTgID), ctx, id)
}

// GetID mocks base method.
func (m *MockUserQuery) GetID(ctx context.Context, id int64) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockUserQueryMockRecorder) GetID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserQuery)(nil).GetID), ctx, id)
}

// GetTgID mocks base method.
func (m *MockUserQuery) GetTgID(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTgID", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTgID indicates an expected call of GetTgID.
func (mr *MockUserQueryMockRecorder) GetTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTgID", reflect.TypeOf((*MockUserQuery)(nil).GetTgID), ctx, id)
}

// MockUserRepoPort is a mock of UserRepoPort interface.
type MockUserRepoPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoPortMockRecorder
	isgomock struct{}
}

// MockUserRepoPortMockRecorder is the mock recorder for MockUserRepoPort.
type MockUserRepoPortMockRecorder struct {
	mock *MockUserRepoPort
}

// NewMockUserRepoPort creates a new mock instance.
func NewMockUserRepoPort(ctrl *gomock.Controller) *MockUserRepoPort {
	mock := &MockUserRepoPort{ctrl: ctrl}
	mock.recorder = &MockUserRepoPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepoPort) EXPECT() *MockUserRepoPortMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserRepoPort) Add(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockUserRepoPortMockRecorder) Add(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserRepoPort)(nil).Add), ctx, user)
}

// DeleteByID mocks base method.
func (m *MockUserRepoPort) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockUserRepoPortMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockUserRepoPort)(nil).DeleteByID), ctx, id)
}

// DeleteByTgID mocks base method.
func (m *MockUserRepoPort) DeleteByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTgID indicates an expected call of DeleteByTgID.
func (mr *MockUserRepoPortMockRecorder) DeleteByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTgID", reflect.TypeOf((*MockUserRepoPort)(nil).DeleteByTgID), ctx, id)
}

// GetByID mocks base method.
func (m *MockUserRepoPort) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoPortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepoPort)(nil).GetByID), ctx, id)
}

// GetByTgID mocks base method.
func (m *MockUserRepoPort) GetByTgID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTgID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTgID indicates an expected call of GetByTgID.
func (mr *MockUserRepoPortMockRecorder) GetByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTgID", reflect.TypeOf((*MockUserRepoPort)(nil).GetByTgID), ctx, id)
}

// GetID mocks base method.
func (m *MockUserRepoPort) GetID(ctx context.Context, id int64) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockUserRepoPortMockRecorder) GetID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserRepoPort)(nil).GetID), ctx, id)
}

// GetTgID mocks base method.
func (m *MockUserRepoPort) GetTgID(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTgID", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTgID indicates an expected call of GetTgID.
func (mr *MockUserRepoPortMockRecorder) GetTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTgID", reflect.TypeOf((*MockUserRepoPort)(nil).GetTgID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockUserRepoPort) UpdateByID(ctx context.Context, id uuid.UUID, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockUserRepoPortMockRecorder) UpdateByID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockUserRepoPort)(nil).UpdateByID), ctx, id, user)
}

// UpdateByTgID mocks base method.
func (m *MockUserRepoPort) UpdateByTgID(ctx context.Context, id int64, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTgID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByTgID indicates an expected call of UpdateByTgID.
func (mr *MockUserRepoPortMockRecorder) UpdateByTgID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTgID", reflect.TypeOf((*MockUserRepoPort)(nil).UpdateByTgID), ctx, id, user)
}

// MockUserCacheInvalidator is a mock of UserCacheInvalidator interface.
type MockUserCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MockUserCacheInvalidatorMockRecorder is the mock recorder for MockUserCacheInvalidator.
type MockUserCacheInvalidatorMockRecorder struct {
	mock *MockUserCacheInvalidator
}

// NewMockUserCacheInvalidator creates a new mock instance.
func NewMockUserCacheInvalidator(ctrl *gomock.Controller) *MockUserCacheInvalidator {
	mock := &MockUserCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockUserCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCacheInvalidator) EXPECT() *MockUserCacheInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateUserByID mocks base method.
func (m *MockUserCacheInvalidator) InvalidateUserByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserByID indicates an expected call of InvalidateUserByID.
func (mr *MockUserCacheInvalidatorMockRecorder) InvalidateUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserByID", reflect.TypeOf((*MockUserCacheInvalidator)(nil).InvalidateUserByID), ctx, id)
}

// InvalidateUserByTgID mocks base method.
func (m *MockUserCacheInvalidator) InvalidateUserByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserByTgID indicates an expected call of InvalidateUserByTgID.
func (mr *MockUserCacheInvalidatorMockRecorder) InvalidateUserByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserByTgID", reflect.TypeOf((*MockUserCacheInvalidator)(nil).InvalidateUserByTgID), ctx, id)
}

// InvalidateUserID mocks base method.
func (m *MockUserCacheInvalidator) InvalidateUserID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserID indicates an expected call of InvalidateUserID.
func (mr *MockUserCacheInvalidatorMockRecorder) InvalidateUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserID", reflect.TypeOf((*MockUserCacheInvalidator)(nil).InvalidateUserID), ctx, id)
}

// InvalidateUserTgID mocks base method.
func (m *MockUserCacheInvalidator) InvalidateUserTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserTgID indicates an expected call of InvalidateUserTgID.
func (mr *MockUserCacheInvalidatorMockRecorder) InvalidateUserTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserTgID", reflect.TypeOf((*MockUserCacheInvalidator)(nil).InvalidateUserTgID), ctx, id)
}

// MockUserCacheCommand is a mock of UserCacheCommand interface.
type MockUserCacheCommand struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheCommandMockRecorder
	isgomock struct{}
}

// MockUserCacheCommandMockRecorder is the mock recorder for MockUserCacheCommand.
type MockUserCacheCommandMockRecorder struct {
	mock *MockUserCacheCommand
}

// NewMockUserCacheCommand creates a new mock instance.
func NewMockUserCacheCommand(ctrl *gomock.Controller) *MockUserCacheCommand {
	mock := &MockUserCacheCommand{ctrl: ctrl}
	mock.recorder = &MockUserCacheCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCacheCommand) EXPECT() *MockUserCacheCommandMockRecorder {
	return m.recorder
}

// AddByID mocks base method.
func (m *MockUserCacheCommand) AddByID(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddByID", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddByID indicates an expected call of AddByID.
func (mr *MockUserCacheCommandMockRecorder) AddByID(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddByID", reflect.TypeOf((*MockUserCacheCommand)(nil).AddByID), ctx, user)
}

// AddByTgID mocks base method.
func (m *MockUserCacheCommand) AddByTgID(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddByTgID", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddByTgID indicates an expected call of AddByTgID.
func (mr *MockUserCacheCommandMockRecorder) AddByTgID(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddByTgID", reflect.TypeOf((*MockUserCacheCommand)(nil).AddByTgID), ctx, user)
}

// AddID mocks base method.
func (m *MockUserCacheCommand) AddID(ctx context.Context, key int64, val uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddID", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddID indicates an expected call of AddID.
func (mr *MockUserCacheCommandMockRecorder) AddID(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddID", reflect.TypeOf((*MockUserCacheCommand)(nil).AddID), ctx, key, val)
}

// AddTgID mocks base method.
func (m *MockUserCacheCommand) AddTgID(ctx context.Context, key uuid.UUID, val int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTgID", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTgID indicates an expected call of AddTgID.
func (mr *MockUserCacheCommandMockRecorder) AddTgID(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTgID", reflect.TypeOf((*MockUserCacheCommand)(nil).AddTgID), ctx, key, val)
}

// MockUserCachePort is a mock of UserCachePort interface.
type MockUserCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockUserCachePortMockRecorder
	isgomock struct{}
}

// MockUserCachePortMockRecorder is the mock recorder for MockUserCachePort.
type MockUserCachePortMockRecorder struct {
	mock *MockUserCachePort
}

// NewMockUserCachePort creates a new mock instance.
func NewMockUserCachePort(ctrl *gomock.Controller) *MockUserCachePort {
	mock := &MockUserCachePort{ctrl: ctrl}
	mock.recorder = &MockUserCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCachePort) EXPECT() *MockUserCachePortMockRecorder {
	return m.recorder
}

// AddByID mocks base method.
func (m *MockUserCachePort) AddByID(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddByID", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddByID indicates an expected call of AddByID.
func (mr *MockUserCachePortMockRecorder) AddByID(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddByID", reflect.TypeOf((*MockUserCachePort)(nil).AddByID), ctx, user)
}

// AddByTgID mocks base method.
func (m *MockUserCachePort) AddByTgID(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddByTgID", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddByTgID indicates an expected call of AddByTgID.
func (mr *MockUserCachePortMockRecorder) AddByTgID(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddByTgID", reflect.TypeOf((*MockUserCachePort)(nil).AddByTgID), ctx, user)
}

// AddID mocks base method.
func (m *MockUserCachePort) AddID(ctx context.Context, key int64, val uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddID", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddID indicates an expected call of AddID.
func (mr *MockUserCachePortMockRecorder) AddID(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddID", reflect.TypeOf((*MockUserCachePort)(nil).AddID), ctx, key, val)
}

// AddTgID mocks base method.
func (m *MockUserCachePort) AddTgID(ctx context.Context, key uuid.UUID, val int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTgID", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTgID indicates an expected call of AddTgID.
func (mr *MockUserCachePortMockRecorder) AddTgID(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTgID", reflect.TypeOf((*MockUserCachePort)(nil).AddTgID), ctx, key, val)
}

// GetByID mocks base method.
func (m *MockUserCachePort) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserCachePortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserCachePort)(nil).GetByID), ctx, id)
}

// GetByTgID mocks base method.
func (m *MockUserCachePort) GetByTgID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTgID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTgID indicates an expected call of GetByTgID.
func (mr *MockUserCachePortMockRecorder) GetByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTgID", reflect.TypeOf((*MockUserCachePort)(nil).GetByTgID), ctx, id)
}

// GetID mocks base method.
func (m *MockUserCachePort) GetID(ctx context.Context, id int64) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockUserCachePortMockRecorder) GetID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserCachePort)(nil).GetID), ctx, id)
}

// GetTgID mocks base method.
func (m *MockUserCachePort) GetTgID(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTgID", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTgID indicates an expected call of GetTgID.
func (mr *MockUserCachePortMockRecorder) GetTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTgID", reflect.TypeOf((*MockUserCachePort)(nil).GetTgID), ctx, id)
}

// InvalidateUserByID mocks base method.
func (m *MockUserCachePort) InvalidateUserByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserByID indicates an expected call of InvalidateUserByID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserByID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserByID), ctx, id)
}

// InvalidateUserByTgID mocks base method.
func (m *MockUserCachePort) InvalidateUserByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserByTgID indicates an expected call of InvalidateUserByTgID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserByTgID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserByTgID), ctx, id)
}

// InvalidateUserID mocks base method.
func (m *MockUserCachePort) InvalidateUserID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserID indicates an expected call of InvalidateUserID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserID), ctx, id)
}

// InvalidateUserTgID mocks base method.
func (m *MockUserCachePort) InvalidateUserTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserTgID indicates an expected call of InvalidateUserTgID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserTgID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserTgID), ctx, id)
}
