// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/tgdb/internal/ports/output.go
//
// Generated by this command:
//
//	mockgen -source=./services/tgdb/internal/ports/output.go -destination=./services/tgdb/pkg/mock/mock_output.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/echo/tgdb/internal/domain/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserCommandPort is a mock of UserCommandPort interface.
type MockUserCommandPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserCommandPortMockRecorder
	isgomock struct{}
}

// MockUserCommandPortMockRecorder is the mock recorder for MockUserCommandPort.
type MockUserCommandPortMockRecorder struct {
	mock *MockUserCommandPort
}

// NewMockUserCommandPort creates a new mock instance.
func NewMockUserCommandPort(ctrl *gomock.Controller) *MockUserCommandPort {
	mock := &MockUserCommandPort{ctrl: ctrl}
	mock.recorder = &MockUserCommandPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCommandPort) EXPECT() *MockUserCommandPortMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserCommandPort) Add(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockUserCommandPortMockRecorder) Add(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserCommandPort)(nil).Add), ctx, user)
}

// DeleteByID mocks base method.
func (m *MockUserCommandPort) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockUserCommandPortMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockUserCommandPort)(nil).DeleteByID), ctx, id)
}

// DeleteByTgID mocks base method.
func (m *MockUserCommandPort) DeleteByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTgID indicates an expected call of DeleteByTgID.
func (mr *MockUserCommandPortMockRecorder) DeleteByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTgID", reflect.TypeOf((*MockUserCommandPort)(nil).DeleteByTgID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockUserCommandPort) UpdateByID(ctx context.Context, id uuid.UUID, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockUserCommandPortMockRecorder) UpdateByID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockUserCommandPort)(nil).UpdateByID), ctx, id, user)
}

// UpdateByTgID mocks base method.
func (m *MockUserCommandPort) UpdateByTgID(ctx context.Context, id int64, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTgID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByTgID indicates an expected call of UpdateByTgID.
func (mr *MockUserCommandPortMockRecorder) UpdateByTgID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTgID", reflect.TypeOf((*MockUserCommandPort)(nil).UpdateByTgID), ctx, id, user)
}

// MockUserQueryPort is a mock of UserQueryPort interface.
type MockUserQueryPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueryPortMockRecorder
	isgomock struct{}
}

// MockUserQueryPortMockRecorder is the mock recorder for MockUserQueryPort.
type MockUserQueryPortMockRecorder struct {
	mock *MockUserQueryPort
}

// NewMockUserQueryPort creates a new mock instance.
func NewMockUserQueryPort(ctrl *gomock.Controller) *MockUserQueryPort {
	mock := &MockUserQueryPort{ctrl: ctrl}
	mock.recorder = &MockUserQueryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueryPort) EXPECT() *MockUserQueryPortMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserQueryPort) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserQueryPortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserQueryPort)(nil).GetByID), ctx, id)
}

// GetByTgID mocks base method.
func (m *MockUserQueryPort) GetByTgID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTgID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTgID indicates an expected call of GetByTgID.
func (mr *MockUserQueryPortMockRecorder) GetByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTgID", reflect.TypeOf((*MockUserQueryPort)(nil).GetByTgID), ctx, id)
}

// GetID mocks base method.
func (m *MockUserQueryPort) GetID(ctx context.Context, id int64) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockUserQueryPortMockRecorder) GetID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserQueryPort)(nil).GetID), ctx, id)
}

// GetTgID mocks base method.
func (m *MockUserQueryPort) GetTgID(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTgID", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTgID indicates an expected call of GetTgID.
func (mr *MockUserQueryPortMockRecorder) GetTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTgID", reflect.TypeOf((*MockUserQueryPort)(nil).GetTgID), ctx, id)
}

// MockUserRepoPort is a mock of UserRepoPort interface.
type MockUserRepoPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoPortMockRecorder
	isgomock struct{}
}

// MockUserRepoPortMockRecorder is the mock recorder for MockUserRepoPort.
type MockUserRepoPortMockRecorder struct {
	mock *MockUserRepoPort
}

// NewMockUserRepoPort creates a new mock instance.
func NewMockUserRepoPort(ctrl *gomock.Controller) *MockUserRepoPort {
	mock := &MockUserRepoPort{ctrl: ctrl}
	mock.recorder = &MockUserRepoPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepoPort) EXPECT() *MockUserRepoPortMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserRepoPort) Add(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockUserRepoPortMockRecorder) Add(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserRepoPort)(nil).Add), ctx, user)
}

// DeleteByID mocks base method.
func (m *MockUserRepoPort) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockUserRepoPortMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockUserRepoPort)(nil).DeleteByID), ctx, id)
}

// DeleteByTgID mocks base method.
func (m *MockUserRepoPort) DeleteByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTgID indicates an expected call of DeleteByTgID.
func (mr *MockUserRepoPortMockRecorder) DeleteByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTgID", reflect.TypeOf((*MockUserRepoPort)(nil).DeleteByTgID), ctx, id)
}

// GetByID mocks base method.
func (m *MockUserRepoPort) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoPortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepoPort)(nil).GetByID), ctx, id)
}

// GetByTgID mocks base method.
func (m *MockUserRepoPort) GetByTgID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTgID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTgID indicates an expected call of GetByTgID.
func (mr *MockUserRepoPortMockRecorder) GetByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTgID", reflect.TypeOf((*MockUserRepoPort)(nil).GetByTgID), ctx, id)
}

// GetID mocks base method.
func (m *MockUserRepoPort) GetID(ctx context.Context, id int64) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockUserRepoPortMockRecorder) GetID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserRepoPort)(nil).GetID), ctx, id)
}

// GetTgID mocks base method.
func (m *MockUserRepoPort) GetTgID(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTgID", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTgID indicates an expected call of GetTgID.
func (mr *MockUserRepoPortMockRecorder) GetTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTgID", reflect.TypeOf((*MockUserRepoPort)(nil).GetTgID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockUserRepoPort) UpdateByID(ctx context.Context, id uuid.UUID, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockUserRepoPortMockRecorder) UpdateByID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockUserRepoPort)(nil).UpdateByID), ctx, id, user)
}

// UpdateByTgID mocks base method.
func (m *MockUserRepoPort) UpdateByTgID(ctx context.Context, id int64, user *models.UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTgID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByTgID indicates an expected call of UpdateByTgID.
func (mr *MockUserRepoPortMockRecorder) UpdateByTgID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTgID", reflect.TypeOf((*MockUserRepoPort)(nil).UpdateByTgID), ctx, id, user)
}

// MockUserCachePort is a mock of UserCachePort interface.
type MockUserCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockUserCachePortMockRecorder
	isgomock struct{}
}

// MockUserCachePortMockRecorder is the mock recorder for MockUserCachePort.
type MockUserCachePortMockRecorder struct {
	mock *MockUserCachePort
}

// NewMockUserCachePort creates a new mock instance.
func NewMockUserCachePort(ctrl *gomock.Controller) *MockUserCachePort {
	mock := &MockUserCachePort{ctrl: ctrl}
	mock.recorder = &MockUserCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCachePort) EXPECT() *MockUserCachePortMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserCachePort) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserCachePortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserCachePort)(nil).GetByID), ctx, id)
}

// GetByTgID mocks base method.
func (m *MockUserCachePort) GetByTgID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTgID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTgID indicates an expected call of GetByTgID.
func (mr *MockUserCachePortMockRecorder) GetByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTgID", reflect.TypeOf((*MockUserCachePort)(nil).GetByTgID), ctx, id)
}

// GetID mocks base method.
func (m *MockUserCachePort) GetID(ctx context.Context, id int64) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetID indicates an expected call of GetID.
func (mr *MockUserCachePortMockRecorder) GetID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserCachePort)(nil).GetID), ctx, id)
}

// GetTgID mocks base method.
func (m *MockUserCachePort) GetTgID(ctx context.Context, id uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTgID", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTgID indicates an expected call of GetTgID.
func (mr *MockUserCachePortMockRecorder) GetTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTgID", reflect.TypeOf((*MockUserCachePort)(nil).GetTgID), ctx, id)
}

// InvalidateUserByID mocks base method.
func (m *MockUserCachePort) InvalidateUserByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserByID indicates an expected call of InvalidateUserByID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserByID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserByID), ctx, id)
}

// InvalidateUserByTgID mocks base method.
func (m *MockUserCachePort) InvalidateUserByTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserByTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserByTgID indicates an expected call of InvalidateUserByTgID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserByTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserByTgID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserByTgID), ctx, id)
}

// InvalidateUserID mocks base method.
func (m *MockUserCachePort) InvalidateUserID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserID indicates an expected call of InvalidateUserID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserID), ctx, id)
}

// InvalidateUserTgID mocks base method.
func (m *MockUserCachePort) InvalidateUserTgID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserTgID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserTgID indicates an expected call of InvalidateUserTgID.
func (mr *MockUserCachePortMockRecorder) InvalidateUserTgID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserTgID", reflect.TypeOf((*MockUserCachePort)(nil).InvalidateUserTgID), ctx, id)
}
