// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: tgdb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TgDB_CreateUser_FullMethodName       = "/TgDB/CreateUser"
	TgDB_GetUserByID_FullMethodName      = "/TgDB/GetUserByID"
	TgDB_GetUserByTgID_FullMethodName    = "/TgDB/GetUserByTgID"
	TgDB_UpdateUserByID_FullMethodName   = "/TgDB/UpdateUserByID"
	TgDB_UpdateUserByTgID_FullMethodName = "/TgDB/UpdateUserByTgID"
	TgDB_DeleteUserByID_FullMethodName   = "/TgDB/DeleteUserByID"
	TgDB_DeleteUserByTgID_FullMethodName = "/TgDB/DeleteUserByTgID"
	TgDB_GetUserID_FullMethodName        = "/TgDB/GetUserID"
	TgDB_GetUserTgID_FullMethodName      = "/TgDB/GetUserTgID"
)

// TgDBClient is the client API for TgDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgDBClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error)
	GetUserByTgID(ctx context.Context, in *GetUserByTgIDRequest, opts ...grpc.CallOption) (*GetUserByTgIDResponse, error)
	UpdateUserByID(ctx context.Context, in *UpdateUserByIDRequest, opts ...grpc.CallOption) (*UpdateUserByIDResponse, error)
	UpdateUserByTgID(ctx context.Context, in *UpdateUserByTgIDRequest, opts ...grpc.CallOption) (*UpdateUserByTgIDResponse, error)
	DeleteUserByID(ctx context.Context, in *DeleteUserByIDRequest, opts ...grpc.CallOption) (*DeleteUserByIDResponse, error)
	DeleteUserByTgID(ctx context.Context, in *DeleteUserByTgIDRequest, opts ...grpc.CallOption) (*DeleteUserByTgIDResponse, error)
	GetUserID(ctx context.Context, in *GetUserIDRequest, opts ...grpc.CallOption) (*GetUserIDResponse, error)
	GetUserTgID(ctx context.Context, in *GetUserTgIDRequest, opts ...grpc.CallOption) (*GetUserTgIDResponse, error)
}

type tgDBClient struct {
	cc grpc.ClientConnInterface
}

func NewTgDBClient(cc grpc.ClientConnInterface) TgDBClient {
	return &tgDBClient{cc}
}

func (c *tgDBClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, TgDB_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByIDResponse)
	err := c.cc.Invoke(ctx, TgDB_GetUserByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) GetUserByTgID(ctx context.Context, in *GetUserByTgIDRequest, opts ...grpc.CallOption) (*GetUserByTgIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByTgIDResponse)
	err := c.cc.Invoke(ctx, TgDB_GetUserByTgID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) UpdateUserByID(ctx context.Context, in *UpdateUserByIDRequest, opts ...grpc.CallOption) (*UpdateUserByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserByIDResponse)
	err := c.cc.Invoke(ctx, TgDB_UpdateUserByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) UpdateUserByTgID(ctx context.Context, in *UpdateUserByTgIDRequest, opts ...grpc.CallOption) (*UpdateUserByTgIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserByTgIDResponse)
	err := c.cc.Invoke(ctx, TgDB_UpdateUserByTgID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) DeleteUserByID(ctx context.Context, in *DeleteUserByIDRequest, opts ...grpc.CallOption) (*DeleteUserByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserByIDResponse)
	err := c.cc.Invoke(ctx, TgDB_DeleteUserByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) DeleteUserByTgID(ctx context.Context, in *DeleteUserByTgIDRequest, opts ...grpc.CallOption) (*DeleteUserByTgIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserByTgIDResponse)
	err := c.cc.Invoke(ctx, TgDB_DeleteUserByTgID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) GetUserID(ctx context.Context, in *GetUserIDRequest, opts ...grpc.CallOption) (*GetUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserIDResponse)
	err := c.cc.Invoke(ctx, TgDB_GetUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgDBClient) GetUserTgID(ctx context.Context, in *GetUserTgIDRequest, opts ...grpc.CallOption) (*GetUserTgIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTgIDResponse)
	err := c.cc.Invoke(ctx, TgDB_GetUserTgID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgDBServer is the server API for TgDB service.
// All implementations must embed UnimplementedTgDBServer
// for forward compatibility.
type TgDBServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIDResponse, error)
	GetUserByTgID(context.Context, *GetUserByTgIDRequest) (*GetUserByTgIDResponse, error)
	UpdateUserByID(context.Context, *UpdateUserByIDRequest) (*UpdateUserByIDResponse, error)
	UpdateUserByTgID(context.Context, *UpdateUserByTgIDRequest) (*UpdateUserByTgIDResponse, error)
	DeleteUserByID(context.Context, *DeleteUserByIDRequest) (*DeleteUserByIDResponse, error)
	DeleteUserByTgID(context.Context, *DeleteUserByTgIDRequest) (*DeleteUserByTgIDResponse, error)
	GetUserID(context.Context, *GetUserIDRequest) (*GetUserIDResponse, error)
	GetUserTgID(context.Context, *GetUserTgIDRequest) (*GetUserTgIDResponse, error)
	mustEmbedUnimplementedTgDBServer()
}

// UnimplementedTgDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTgDBServer struct{}

func (UnimplementedTgDBServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedTgDBServer) GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (UnimplementedTgDBServer) GetUserByTgID(context.Context, *GetUserByTgIDRequest) (*GetUserByTgIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByTgID not implemented")
}
func (UnimplementedTgDBServer) UpdateUserByID(context.Context, *UpdateUserByIDRequest) (*UpdateUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserByID not implemented")
}
func (UnimplementedTgDBServer) UpdateUserByTgID(context.Context, *UpdateUserByTgIDRequest) (*UpdateUserByTgIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserByTgID not implemented")
}
func (UnimplementedTgDBServer) DeleteUserByID(context.Context, *DeleteUserByIDRequest) (*DeleteUserByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserByID not implemented")
}
func (UnimplementedTgDBServer) DeleteUserByTgID(context.Context, *DeleteUserByTgIDRequest) (*DeleteUserByTgIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserByTgID not implemented")
}
func (UnimplementedTgDBServer) GetUserID(context.Context, *GetUserIDRequest) (*GetUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserID not implemented")
}
func (UnimplementedTgDBServer) GetUserTgID(context.Context, *GetUserTgIDRequest) (*GetUserTgIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTgID not implemented")
}
func (UnimplementedTgDBServer) mustEmbedUnimplementedTgDBServer() {}
func (UnimplementedTgDBServer) testEmbeddedByValue()              {}

// UnsafeTgDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgDBServer will
// result in compilation errors.
type UnsafeTgDBServer interface {
	mustEmbedUnimplementedTgDBServer()
}

func RegisterTgDBServer(s grpc.ServiceRegistrar, srv TgDBServer) {
	// If the following call pancis, it indicates UnimplementedTgDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TgDB_ServiceDesc, srv)
}

func _TgDB_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_GetUserByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).GetUserByID(ctx, req.(*GetUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_GetUserByTgID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByTgIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).GetUserByTgID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_GetUserByTgID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).GetUserByTgID(ctx, req.(*GetUserByTgIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_UpdateUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).UpdateUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_UpdateUserByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).UpdateUserByID(ctx, req.(*UpdateUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_UpdateUserByTgID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserByTgIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).UpdateUserByTgID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_UpdateUserByTgID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).UpdateUserByTgID(ctx, req.(*UpdateUserByTgIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_DeleteUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).DeleteUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_DeleteUserByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).DeleteUserByID(ctx, req.(*DeleteUserByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_DeleteUserByTgID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserByTgIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).DeleteUserByTgID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_DeleteUserByTgID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).DeleteUserByTgID(ctx, req.(*DeleteUserByTgIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_GetUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).GetUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_GetUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).GetUserID(ctx, req.(*GetUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgDB_GetUserTgID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTgIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgDBServer).GetUserTgID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgDB_GetUserTgID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgDBServer).GetUserTgID(ctx, req.(*GetUserTgIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TgDB_ServiceDesc is the grpc.ServiceDesc for TgDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TgDB",
	HandlerType: (*TgDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _TgDB_CreateUser_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _TgDB_GetUserByID_Handler,
		},
		{
			MethodName: "GetUserByTgID",
			Handler:    _TgDB_GetUserByTgID_Handler,
		},
		{
			MethodName: "UpdateUserByID",
			Handler:    _TgDB_UpdateUserByID_Handler,
		},
		{
			MethodName: "UpdateUserByTgID",
			Handler:    _TgDB_UpdateUserByTgID_Handler,
		},
		{
			MethodName: "DeleteUserByID",
			Handler:    _TgDB_DeleteUserByID_Handler,
		},
		{
			MethodName: "DeleteUserByTgID",
			Handler:    _TgDB_DeleteUserByTgID_Handler,
		},
		{
			MethodName: "GetUserID",
			Handler:    _TgDB_GetUserID_Handler,
		},
		{
			MethodName: "GetUserTgID",
			Handler:    _TgDB_GetUserTgID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tgdb.proto",
}
