// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tgdb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	TgId          int64                  `protobuf:"varint,2,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	TgUsername    *string                `protobuf:"bytes,3,opt,name=tg_username,json=tgUsername,proto3,oneof" json:"tg_username,omitempty"`
	Lang          string                 `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix nano timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tgdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *User) GetTgUsername() string {
	if x != nil && x.TgUsername != nil {
		return *x.TgUsername
	}
	return ""
}

func (x *User) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_tgdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_tgdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{2}
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_tgdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_tgdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTgIDRequest) Reset() {
	*x = GetUserByTgIDRequest{}
	mi := &file_tgdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTgIDRequest) ProtoMessage() {}

func (x *GetUserByTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTgIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTgIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByTgIDRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type GetUserByTgIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTgIDResponse) Reset() {
	*x = GetUserByTgIDResponse{}
	mi := &file_tgdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTgIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTgIDResponse) ProtoMessage() {}

func (x *GetUserByTgIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTgIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByTgIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByTgIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgUsername    *string                `protobuf:"bytes,1,opt,name=tg_username,json=tgUsername,proto3,oneof" json:"tg_username,omitempty"`
	Lang          *string                `protobuf:"bytes,2,opt,name=lang,proto3,oneof" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdate) Reset() {
	*x = UserUpdate{}
	mi := &file_tgdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdate) ProtoMessage() {}

func (x *UserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdate.ProtoReflect.Descriptor instead.
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{7}
}

func (x *UserUpdate) GetTgUsername() string {
	if x != nil && x.TgUsername != nil {
		return *x.TgUsername
	}
	return ""
}

func (x *UserUpdate) GetLang() string {
	if x != nil && x.Lang != nil {
		return *x.Lang
	}
	return ""
}

type UpdateUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	Update        *UserUpdate            `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserByIDRequest) Reset() {
	*x = UpdateUserByIDRequest{}
	mi := &file_tgdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserByIDRequest) ProtoMessage() {}

func (x *UpdateUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserByIDRequest) GetUpdate() *UserUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserByIDResponse) Reset() {
	*x = UpdateUserByIDResponse{}
	mi := &file_tgdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserByIDResponse) ProtoMessage() {}

func (x *UpdateUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserByIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{9}
}

type UpdateUserByTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Update        *UserUpdate            `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserByTgIDRequest) Reset() {
	*x = UpdateUserByTgIDRequest{}
	mi := &file_tgdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserByTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserByTgIDRequest) ProtoMessage() {}

func (x *UpdateUserByTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserByTgIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserByTgIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserByTgIDRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *UpdateUserByTgIDRequest) GetUpdate() *UserUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateUserByTgIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserByTgIDResponse) Reset() {
	*x = UpdateUserByTgIDResponse{}
	mi := &file_tgdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserByTgIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserByTgIDResponse) ProtoMessage() {}

func (x *UpdateUserByTgIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserByTgIDResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserByTgIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{11}
}

type DeleteUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserByIDRequest) Reset() {
	*x = DeleteUserByIDRequest{}
	mi := &file_tgdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserByIDRequest) ProtoMessage() {}

func (x *DeleteUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserByIDResponse) Reset() {
	*x = DeleteUserByIDResponse{}
	mi := &file_tgdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserByIDResponse) ProtoMessage() {}

func (x *DeleteUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserByIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{13}
}

type DeleteUserByTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserByTgIDRequest) Reset() {
	*x = DeleteUserByTgIDRequest{}
	mi := &file_tgdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserByTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserByTgIDRequest) ProtoMessage() {}

func (x *DeleteUserByTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserByTgIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserByTgIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserByTgIDRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type DeleteUserByTgIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserByTgIDResponse) Reset() {
	*x = DeleteUserByTgIDResponse{}
	mi := &file_tgdb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserByTgIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserByTgIDResponse) ProtoMessage() {}

func (x *DeleteUserByTgIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserByTgIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserByTgIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{15}
}

type GetUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDRequest) Reset() {
	*x = GetUserIDRequest{}
	mi := &file_tgdb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDRequest) ProtoMessage() {}

func (x *GetUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserIDRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type GetUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDResponse) Reset() {
	*x = GetUserIDResponse{}
	mi := &file_tgdb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDResponse) ProtoMessage() {}

func (x *GetUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTgIDRequest) Reset() {
	*x = GetUserTgIDRequest{}
	mi := &file_tgdb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTgIDRequest) ProtoMessage() {}

func (x *GetUserTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTgIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserTgIDRequest) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserTgIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserTgIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTgIDResponse) Reset() {
	*x = GetUserTgIDResponse{}
	mi := &file_tgdb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTgIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTgIDResponse) ProtoMessage() {}

func (x *GetUserTgIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tgdb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTgIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserTgIDResponse) Descriptor() ([]byte, []int) {
	return file_tgdb_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserTgIDResponse) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

var File_tgdb_proto protoreflect.FileDescriptor

const file_tgdb_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tgdb.proto\x12\x04tgdb\"\x94\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05tg_id\x18\x02 \x01(\x03R\x04tgId\x12$\n" +
	"\vtg_username\x18\x03 \x01(\tH\x00R\n" +
	"tgUsername\x88\x01\x01\x12\x12\n" +
	"\x04lang\x18\x04 \x01(\tR\x04lang\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAtB\x0e\n" +
	"\f_tg_username\"3\n" +
	"\x11CreateUserRequest\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".tgdb.UserR\x04user\"\x14\n" +
	"\x12CreateUserResponse\"$\n" +
	"\x12GetUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x13GetUserByIDResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".tgdb.UserR\x04user\"+\n" +
	"\x14GetUserByTgIDRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\"7\n" +
	"\x15GetUserByTgIDResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".tgdb.UserR\x04user\"d\n" +
	"\n" +
	"UserUpdate\x12$\n" +
	"\vtg_username\x18\x01 \x01(\tH\x00R\n" +
	"tgUsername\x88\x01\x01\x12\x17\n" +
	"\x04lang\x18\x02 \x01(\tH\x01R\x04lang\x88\x01\x01B\x0e\n" +
	"\f_tg_usernameB\a\n" +
	"\x05_lang\"Q\n" +
	"\x15UpdateUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06update\x18\x02 \x01(\v2\x10.tgdb.UserUpdateR\x06update\"\x18\n" +
	"\x16UpdateUserByIDResponse\"X\n" +
	"\x17UpdateUserByTgIDRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\x12(\n" +
	"\x06update\x18\x02 \x01(\v2\x10.tgdb.UserUpdateR\x06update\"\x1a\n" +
	"\x18UpdateUserByTgIDResponse\"'\n" +
	"\x15DeleteUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteUserByIDResponse\".\n" +
	"\x17DeleteUserByTgIDRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\"\x1a\n" +
	"\x18DeleteUserByTgIDResponse\"'\n" +
	"\x10GetUserIDRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\"#\n" +
	"\x11GetUserIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12GetUserTgIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x13GetUserTgIDResponse\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId2\x97\x05\n" +
	"\x04TgDB\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.tgdb.CreateUserRequest\x1a\x18.tgdb.CreateUserResponse\x12B\n" +
	"\vGetUserByID\x12\x18.tgdb.GetUserByIDRequest\x1a\x19.tgdb.GetUserByIDResponse\x12H\n" +
	"\rGetUserByTgID\x12\x1a.tgdb.GetUserByTgIDRequest\x1a\x1b.tgdb.GetUserByTgIDResponse\x12K\n" +
	"\x0eUpdateUserByID\x12\x1b.tgdb.UpdateUserByIDRequest\x1a\x1c.tgdb.UpdateUserByIDResponse\x12Q\n" +
	"\x10UpdateUserByTgID\x12\x1d.tgdb.UpdateUserByTgIDRequest\x1a\x1e.tgdb.UpdateUserByTgIDResponse\x12K\n" +
	"\x0eDeleteUserByID\x12\x1b.tgdb.DeleteUserByIDRequest\x1a\x1c.tgdb.DeleteUserByIDResponse\x12Q\n" +
	"\x10DeleteUserByTgID\x12\x1d.tgdb.DeleteUserByTgIDRequest\x1a\x1e.tgdb.DeleteUserByTgIDResponse\x12<\n" +
	"\tGetUserID\x12\x16.tgdb.GetUserIDRequest\x1a\x17.tgdb.GetUserIDResponse\x12B\n" +
	"\vGetUserTgID\x12\x18.tgdb.GetUserTgIDRequest\x1a\x19.tgdb.GetUserTgIDResponseB\tZ\a./protob\x06proto3"

var (
	file_tgdb_proto_rawDescOnce sync.Once
	file_tgdb_proto_rawDescData []byte
)

func file_tgdb_proto_rawDescGZIP() []byte {
	file_tgdb_proto_rawDescOnce.Do(func() {
		file_tgdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tgdb_proto_rawDesc), len(file_tgdb_proto_rawDesc)))
	})
	return file_tgdb_proto_rawDescData
}

var file_tgdb_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_tgdb_proto_goTypes = []any{
	(*User)(nil),                     // 0: tgdb.User
	(*CreateUserRequest)(nil),        // 1: tgdb.CreateUserRequest
	(*CreateUserResponse)(nil),       // 2: tgdb.CreateUserResponse
	(*GetUserByIDRequest)(nil),       // 3: tgdb.GetUserByIDRequest
	(*GetUserByIDResponse)(nil),      // 4: tgdb.GetUserByIDResponse
	(*GetUserByTgIDRequest)(nil),     // 5: tgdb.GetUserByTgIDRequest
	(*GetUserByTgIDResponse)(nil),    // 6: tgdb.GetUserByTgIDResponse
	(*UserUpdate)(nil),               // 7: tgdb.UserUpdate
	(*UpdateUserByIDRequest)(nil),    // 8: tgdb.UpdateUserByIDRequest
	(*UpdateUserByIDResponse)(nil),   // 9: tgdb.UpdateUserByIDResponse
	(*UpdateUserByTgIDRequest)(nil),  // 10: tgdb.UpdateUserByTgIDRequest
	(*UpdateUserByTgIDResponse)(nil), // 11: tgdb.UpdateUserByTgIDResponse
	(*DeleteUserByIDRequest)(nil),    // 12: tgdb.DeleteUserByIDRequest
	(*DeleteUserByIDResponse)(nil),   // 13: tgdb.DeleteUserByIDResponse
	(*DeleteUserByTgIDRequest)(nil),  // 14: tgdb.DeleteUserByTgIDRequest
	(*DeleteUserByTgIDResponse)(nil), // 15: tgdb.DeleteUserByTgIDResponse
	(*GetUserIDRequest)(nil),         // 16: tgdb.GetUserIDRequest
	(*GetUserIDResponse)(nil),        // 17: tgdb.GetUserIDResponse
	(*GetUserTgIDRequest)(nil),       // 18: tgdb.GetUserTgIDRequest
	(*GetUserTgIDResponse)(nil),      // 19: tgdb.GetUserTgIDResponse
}
var file_tgdb_proto_depIdxs = []int32{
	0,  // 0: tgdb.CreateUserRequest.user:type_name -> tgdb.User
	0,  // 1: tgdb.GetUserByIDResponse.user:type_name -> tgdb.User
	0,  // 2: tgdb.GetUserByTgIDResponse.user:type_name -> tgdb.User
	7,  // 3: tgdb.UpdateUserByIDRequest.update:type_name -> tgdb.UserUpdate
	7,  // 4: tgdb.UpdateUserByTgIDRequest.update:type_name -> tgdb.UserUpdate
	1,  // 5: tgdb.TgDB.CreateUser:input_type -> tgdb.CreateUserRequest
	3,  // 6: tgdb.TgDB.GetUserByID:input_type -> tgdb.GetUserByIDRequest
	5,  // 7: tgdb.TgDB.GetUserByTgID:input_type -> tgdb.GetUserByTgIDRequest
	8,  // 8: tgdb.TgDB.UpdateUserByID:input_type -> tgdb.UpdateUserByIDRequest
	10, // 9: tgdb.TgDB.UpdateUserByTgID:input_type -> tgdb.UpdateUserByTgIDRequest
	12, // 10: tgdb.TgDB.DeleteUserByID:input_type -> tgdb.DeleteUserByIDRequest
	14, // 11: tgdb.TgDB.DeleteUserByTgID:input_type -> tgdb.DeleteUserByTgIDRequest
	16, // 12: tgdb.TgDB.GetUserID:input_type -> tgdb.GetUserIDRequest
	18, // 13: tgdb.TgDB.GetUserTgID:input_type -> tgdb.GetUserTgIDRequest
	2,  // 14: tgdb.TgDB.CreateUser:output_type -> tgdb.CreateUserResponse
	4,  // 15: tgdb.TgDB.GetUserByID:output_type -> tgdb.GetUserByIDResponse
	6,  // 16: tgdb.TgDB.GetUserByTgID:output_type -> tgdb.GetUserByTgIDResponse
	9,  // 17: tgdb.TgDB.UpdateUserByID:output_type -> tgdb.UpdateUserByIDResponse
	11, // 18: tgdb.TgDB.UpdateUserByTgID:output_type -> tgdb.UpdateUserByTgIDResponse
	13, // 19: tgdb.TgDB.DeleteUserByID:output_type -> tgdb.DeleteUserByIDResponse
	15, // 20: tgdb.TgDB.DeleteUserByTgID:output_type -> tgdb.DeleteUserByTgIDResponse
	17, // 21: tgdb.TgDB.GetUserID:output_type -> tgdb.GetUserIDResponse
	19, // 22: tgdb.TgDB.GetUserTgID:output_type -> tgdb.GetUserTgIDResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tgdb_proto_init() }
func file_tgdb_proto_init() {
	if File_tgdb_proto != nil {
		return
	}
	file_tgdb_proto_msgTypes[0].OneofWrappers = []any{}
	file_tgdb_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tgdb_proto_rawDesc), len(file_tgdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tgdb_proto_goTypes,
		DependencyIndexes: file_tgdb_proto_depIdxs,
		MessageInfos:      file_tgdb_proto_msgTypes,
	}.Build()
	File_tgdb_proto = out.File
	file_tgdb_proto_goTypes = nil
	file_tgdb_proto_depIdxs = nil
}
