apiVersion: v1
kind: ConfigMap

metadata:
  name: tgbot-config
  namespace: dev

data:
  S3_URL: "http://s3-0.s3:9000"
  TGDB_HOST: "tgdb"
  TGDB_PORT: "50051"
  KAFKA_BOOTSTRAP_SERVERS: '["kafka-0.kafka:9092"]'
  KAFKA_CONSUMER_GROUP: "tg_bot"
  BOT_API_MODE: "webhook"
  DEFAULT_LOCALE: "en"
  LOG_LEVEL: "debug"