apiVersion: v1
kind: Service

metadata:
  name: jaeger
  namespace: dev

spec:
  clusterIP: None
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP